name: Build and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phonebook-frontend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: (Frontend) Install dependencies
        run: npm ci
      - name: (Frontend) Lint
        run: npm run lint

  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phonebook-backend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: (Backend) Install dependencies
        run: npm ci
      - name: (Backend) Lint
        run: npm run lint

  full-build:
    runs-on: ubuntu-latest
    needs: [lint-backend, lint-frontend]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: (Frontend) Install dependencies
        run: npm --prefix phonebook-frontend ci
      - name: (Backend) Install dependencies
        run: npm --prefix phonebook-backend ci
      - name: (Backend) Full Build
        run: npm --prefix phonebook-backend run build:ui

  tag-release:
    needs: [full-build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}