name: Build and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: (Frontend) Install dependencies
        run: npm --prefix phonebook-frontend ci
      - name: (Frontend) Lint
        run: npm --prefix phonebook-frontend run lint

      - name: (Backend) Install dependencies
        run: npm --prefix phonebook-backend ci
      - name: (Backend) Lint
        run: npm --prefix phonebook-backend run lint
      - name: (Backend) Full Build
        run: npm --prefix phonebook-backend run